version: "3"

services:
  web:
    image: car_acceptance_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"