version: "3"

services:
  web:
    image: car_acceptance_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"
    network_mode: bridge
    command: nodemon src/server.js
    ports:
      - "8080:8080"
  test:
    image: car_acceptance_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm test
  autocannon:
    image: car_acceptance_backend
    network_mode: bridge
    links:
      - web
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npx autocannon -c 100 -d 5 web:8080/