version: "3"
services:
  web:
    image: rusanovnd/car_acceptance_backend:1.0.0
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
networks:
  webnet: