version: "3"

services:
  web:
    image: car_acceptance_backend
    container_name: web
    restart: always
    links:
      - mongo
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"
    network_mode: bridge
    command: nodemon src/server.js
    ports:
      - "8080:8080"
  mongo:
    container_name: mongo
    image: mongo
    network_mode: bridge
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  test:
    image: car_acceptance_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm test
  autocannon:
    image: car_acceptance_backend
    network_mode: bridge
    links:
      - web
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npx autocannon -c 100 -d 5 web:8080/