version: "3"

services:
  web-dev:
    image: $IP_SERVER:$PORT_REGISTRY_SERVER/car_acceptance_backend:latest
    container_name: car_acceptance_backend--dev
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"
    network_mode: bridge
    command: nodemon --watch 'src/**/*' -e ts,tsx --exec npm run start:dev
    ports:
      - "8080:8080"
  web-prod:
    image: $IP_SERVER:$PORT_REGISTRY_SERVER/car_acceptance_backend:latest
    container_name: car_acceptance_backend--prod
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"
    network_mode: bridge
    command: npm run start:prod
    ports:
      - "8080:8080"
  mongo:
    container_name: mongo
    image: mongo
    network_mode: bridge
    user: root
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      MONGO_INITDB_DATABASE: car_acceptance
  test:
    image: $IP_SERVER:$PORT_REGISTRY_SERVER/car_acceptance_backend:latest
    depends_on:
      - mongo
    links:
      - mongo
    network_mode: bridge
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c 'npm test'
  autocannon:
    image: $IP_SERVER:$PORT_REGISTRY_SERVER/car_acceptance_backend:latest
    network_mode: bridge
    links:
      - web-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npx autocannon -c 100 -d 5 web:8080/